<?xml version="1.0" encoding="utf-8"?><Database Name="Camera_Store" Class="ModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Camera_Store;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="Camera_StoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Addresses" Member="Addresses">
    <Type Name="Address">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_ExportBill" Member="ExportBills" ThisKey="UserID" OtherKey="EmployeeID" Type="ExportBill" />
      <Association Name="User_Order" Member="Orders" ThisKey="UserID" OtherKey="EmployeeID" Type="Order" />
      <Association Name="Role_User" Member="Role" ThisKey="RoleID" OtherKey="RoleID" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Banners" Member="Banners">
    <Type Name="Banner">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BannerPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BannerAlt" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExportBills" Member="ExportBills">
    <Type Name="ExportBill">
      <Column Name="BillID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExportedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_ExportBill" Member="User" ThisKey="EmployeeID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="Order_ExportBill" Member="Order" ThisKey="OrderID" OtherKey="OrderID" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewsletterCategories" Member="NewsletterCategories">
    <Type Name="NewsletterCategory">
      <Column Name="CateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CateName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NewsletterCategory_Newsletter" Member="Newsletters" ThisKey="CateID" OtherKey="CateID" Type="Newsletter" />
    </Type>
  </Table>
  <Table Name="dbo.Newsletters" Member="Newsletters">
    <Type Name="Newsletter">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Subtitle" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Viewed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NewsletterCategory_Newsletter" Member="NewsletterCategory" ThisKey="CateID" OtherKey="CateID" Type="NewsletterCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderProvince" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderDistinct" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipAddress" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ShipProvince" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipDisctrict" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipNote" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ShipDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_ExportBill" Member="ExportBills" ThisKey="OrderID" OtherKey="OrderID" Type="ExportBill" />
      <Association Name="Order_OrdersDetail" Member="OrdersDetails" ThisKey="OrderID" OtherKey="OrderID" Type="OrdersDetail" />
      <Association Name="User_Order" Member="User" ThisKey="EmployeeID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdersDetail" Member="OrdersDetails">
    <Type Name="OrdersDetail">
      <Column Name="Serial" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Order_OrdersDetail" Member="Order" ThisKey="OrderID" OtherKey="OrderID" Type="Order" IsForeignKey="true" />
      <Association Name="Product_OrdersDetail" Member="Product" ThisKey="ProductID" OtherKey="Serial" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Others" Member="Others">
    <Type Name="Other">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductCategories" Member="ProductCategories">
    <Type Name="ProductCategory">
      <Column Name="CateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CateParentsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CateName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Icon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ProductCategory_Product" Member="Products" ThisKey="CateID" OtherKey="CateID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="Serial" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductID" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Information" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Introduction" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Parameters" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UnitInStock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitOnOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Viewed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bought" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Product_OrdersDetail" Member="OrdersDetails" ThisKey="Serial" OtherKey="ProductID" Type="OrdersDetail" />
      <Association Name="Product_PromotionProduct" Member="PromotionProducts" ThisKey="Serial" OtherKey="ProductID" Type="PromotionProduct" />
      <Association Name="ProductCategory_Product" Member="ProductCategory" ThisKey="CateID" OtherKey="CateID" Type="ProductCategory" IsForeignKey="true" />
      <Association Name="Supplier_Product" Member="Supplier" ThisKey="SupplierID" OtherKey="SupplierID" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PromotionProducts" Member="PromotionProducts">
    <Type Name="PromotionProduct">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BeginDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Product_PromotionProduct" Member="Product" ThisKey="ProductID" OtherKey="Serial" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Role_User" Member="Users" ThisKey="RoleID" OtherKey="RoleID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Slideshows" Member="Slideshows">
    <Type Name="Slideshow">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ThumbnailPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Suppliers" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SupplierName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Supplier_Product" Member="Products" ThisKey="SupplierID" OtherKey="SupplierID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Supports" Member="Supports">
    <Type Name="Support">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SkypeNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SkypeUrl" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AvatarPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>